// Generated by ts-to-zod
import { z } from "zod";

export const systemDataTelemetryPointSchema = z.object({
    type: z.string(),
    version: z.number(),
    seq: z.number(),
    timestampUtc: z.string(),
    lat: z.number(),
    lon: z.number(),
    altitudeMetres: z.number(),
    groundSpeedKmh: z.number(),
    headingDegrees: z.number(),
    batteryVolts: z.number(),
    receivedTimeUtc: z.string(),
    connectionStatus: z.string()
});
